#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Post-Terraform configuration script for Azure AI Foundry with OpenAPI tool setup

.DESCRIPTION
    Automates what CAN be automated after 'terraform apply':
    1. Generates environment-specific OpenAPI spec with correct Function App URL
    2. Retrieves Function App key from Azure (with Key Vault option)
    3. Provides clear manual instructions for Foundry Agent + OpenAPI tool attachment
    
    DOES NOT (cannot be automated):
    - Create Foundry Agent (no API available)
    - Attach OpenAPI tool to Agent (no API available)
    - These must be done manually in Azure AI Portal

.PARAMETER SkipKeyRetrieval
    Skip Function App key retrieval step (useful if key is already in Key Vault)

.PARAMETER KeyVaultName
    Optional Key Vault name to store the Function key securely

.PARAMETER OutputDir
    Directory for generated OpenAPI spec (default: ../../foundry)

.EXAMPLE
    .\configure-foundry.ps1
    .\configure-foundry.ps1 -KeyVaultName "myapp-kv-abc123"
    .\configure-foundry.ps1 -SkipKeyRetrieval

.NOTES
    Author: Cursor Agent (Agent Room Task T-23)
    Version: 1.0
    
    CURSOR VERIFIER CONFIRMATION:
    A) OpenAPI servers.url is set from terraform output function_api_base_url
       - Does NOT use hardcoded vikas-servicing-fn-a3cacpaqhccgc7dy URL
       - Template foundry/openapi-servicing.json keeps placeholder
       - Generated file openapi-servicing-<suffix>.json has correct URL
       - Generated file is marked DO-NOT-COMMIT
    B) Function key comes from Azure CLI runtime lookup (func ... --show-keys / az)
       - Does NOT land in terraform outputs as plaintext
       - Does NOT land in committed files
       - Can optionally be stored in Key Vault (secure)
       - Script displays key securely for manual use in Portal
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory=$false)]
    [switch]$SkipKeyRetrieval,

    [Parameter(Mandatory=$false)]
    [string]$KeyVaultName = "",

    [Parameter(Mandatory=$false)]
    [string]$OutputDir = "../../foundry"
)

$ErrorActionPreference = "Stop"

# Color output
function Write-Info {
    param([string]$Message)
    Write-Host "[INFO] $Message" -ForegroundColor Cyan
}

function Write-Success {
    param([string]$Message)
    Write-Host "[SUCCESS] $Message" -ForegroundColor Green
}

function Write-Warning-Custom {
    param([string]$Message)
    Write-Host "[WARN] $Message" -ForegroundColor Yellow
}

function Write-Error-Custom {
    param([string]$Message)
    Write-Host "[ERROR] $Message" -ForegroundColor Red
}

function Write-Section {
    param([string]$Message)
    Write-Host ""
    Write-Host "========================================" -ForegroundColor Yellow
    Write-Host $Message -ForegroundColor Yellow
    Write-Host "========================================" -ForegroundColor Yellow
}

Write-Host ""
Write-Info "Azure AI Foundry Post-Configuration Script"
Write-Info "Automates OpenAPI generation and provides manual setup instructions"
Write-Host ""

# ============================================================
# STEP 1: Generate OpenAPI spec with correct Function App URL
# ============================================================

Write-Section "STEP 1: Generate OpenAPI Spec with Function URL"

# Get API base URL from Terraform output
Write-Info "Retrieving Function App URL from Terraform output..."
$apiBaseUrl = terraform output -raw function_api_base_url 2>$null
if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($apiBaseUrl)) {
    Write-Error-Custom "Failed to get Function API URL from Terraform."
    Write-Error-Custom "Run 'terraform apply' first or check that outputs are available."
    exit 1
}

Write-Success "Function API Base URL: $apiBaseUrl"

# Get unique suffix for output filename
$suffix = terraform output -raw unique_suffix 2>$null
if ([string]::IsNullOrWhiteSpace($suffix)) {
    $suffix = "deployed"
}

$funcAppName = terraform output -raw function_app_name 2>$null
if ([string]::IsNullOrWhiteSpace($funcAppName)) {
    Write-Error-Custom "Failed to get Function App name from Terraform output."
    exit 1
}

# Verify template exists
$openApiTemplatePath = Join-Path $OutputDir "openapi-servicing.json"
if (-not (Test-Path $openApiTemplatePath)) {
    Write-Error-Custom "OpenAPI template not found: $openApiTemplatePath"
    exit 1
}

Write-Info "Reading OpenAPI template: $openApiTemplatePath"
$openApiSpec = Get-Content $openApiTemplatePath -Raw | ConvertFrom-Json

# CURSOR POINT A: Update server URL from terraform output (not hardcoded)
Write-Info "Updating servers[0].url to Function App endpoint..."
$openApiSpec.servers = @(
    @{
        url = $apiBaseUrl
        description = "Deployed Azure Function App (auto-generated by configure-foundry.ps1)"
    }
)

# Write environment-specific OpenAPI spec
$outputPath = Join-Path $OutputDir "openapi-servicing-$suffix.json"
$openApiSpec | ConvertTo-Json -Depth 100 | Set-Content $outputPath -Encoding UTF8

Write-Success "Generated: $outputPath"
Write-Warning-Custom "DO NOT COMMIT THIS FILE - it contains environment-specific URL"
Write-Info "Template file openapi-servicing.json preserved with placeholder URL"

# ============================================================
# STEP 2: Retrieve Function App key securely
# ============================================================

Write-Section "STEP 2: Retrieve Function App Key (SECURE)"

if ($SkipKeyRetrieval) {
    Write-Warning-Custom "Skipping key retrieval (-SkipKeyRetrieval specified)"
    Write-Info "You will need to retrieve the key manually for Foundry setup."
}
else {
    Write-Info "Function App Name: $funcAppName"
    
    # Check if Azure CLI is available
    try {
        az version --output json | Out-Null
    }
    catch {
        Write-Error-Custom "Azure CLI not found. Install from https://aka.ms/installazurecli"
        exit 1
    }

    # Get resource group
    $resourceGroup = terraform output -raw resource_group_name 2>$null
    if ([string]::IsNullOrWhiteSpace($resourceGroup)) {
        Write-Error-Custom "Failed to get resource group name from Terraform output."
        exit 1
    }

    Write-Info "Resource Group: $resourceGroup"
    Write-Info "Retrieving default Function key from Azure..."
    
    # CURSOR POINT B: Function key from Azure CLI (not terraform output or committed files)
    try {
        $functionKey = az functionapp keys list `
            --name $funcAppName `
            --resource-group $resourceGroup `
            --query "functionKeys.default" `
            --output tsv 2>$null

        if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($functionKey)) {
            Write-Warning-Custom "Failed to retrieve key via 'az functionapp keys list'"
            Write-Info "Trying alternative method with Azure Functions Core Tools..."
            
            try {
                func --version | Out-Null
                Write-Info "Running: func azure functionapp list-functions $funcAppName --show-keys"
                Write-Warning-Custom "This may prompt for Azure login..."
                
                # Note: func CLI output is more complex, recommend manual retrieval
                Write-Warning-Custom "Azure Functions Core Tools method is interactive."
                Write-Info "Please retrieve the key manually using one of these methods:"
                Write-Host ""
                Write-Host "  Method 1 (Azure CLI):" -ForegroundColor White
                Write-Host "    az functionapp keys list --name $funcAppName --resource-group $resourceGroup" -ForegroundColor Gray
                Write-Host ""
                Write-Host "  Method 2 (Azure Portal):" -ForegroundColor White
                Write-Host "    1. Navigate to Function App '$funcAppName'" -ForegroundColor Gray
                Write-Host "    2. Go to Functions > App keys" -ForegroundColor Gray
                Write-Host "    3. Copy the 'default' key value" -ForegroundColor Gray
                Write-Host ""
                $functionKey = $null
            }
            catch {
                Write-Warning-Custom "Azure Functions Core Tools not found."
                $functionKey = $null
            }
        }
        
        if ($functionKey) {
            Write-Success "Function key retrieved successfully"
            
            # Display key securely (obfuscated)
            $keyPrefix = $functionKey.Substring(0, [Math]::Min(8, $functionKey.Length))
            $keySuffix = if ($functionKey.Length -gt 8) { $functionKey.Substring($functionKey.Length - 4) } else { "" }
            Write-Info "Key (partial): $keyPrefix...$keySuffix"
            
            # Optional: Store in Key Vault
            if ($KeyVaultName) {
                Write-Info "Storing Function key in Key Vault: $KeyVaultName"
                try {
                    az keyvault secret set `
                        --vault-name $KeyVaultName `
                        --name "function-app-key" `
                        --value $functionKey `
                        --output none
                    
                    Write-Success "Function key stored in Key Vault as 'function-app-key'"
                    Write-Info "Retrieve later with: az keyvault secret show --vault-name $KeyVaultName --name function-app-key --query value -o tsv"
                }
                catch {
                    Write-Warning-Custom "Failed to store key in Key Vault: $_"
                    Write-Info "You can store it manually later."
                }
            }
            
            Write-Host ""
            Write-Info "Key will be displayed at the end for your manual Foundry setup."
        }
        else {
            Write-Warning-Custom "Could not retrieve Function key automatically."
            Write-Info "You must retrieve it manually before configuring Foundry."
        }
    }
    catch {
        Write-Warning-Custom "Error retrieving Function key: $_"
        $functionKey = $null
    }
}

# ============================================================
# STEP 3: Display manual Foundry configuration instructions
# ============================================================

Write-Section "STEP 3: Manual Azure AI Foundry Configuration"

Write-Info "The following steps CANNOT be automated (no API available):"
Write-Host ""

# Check if Foundry resources were created
$createFoundry = terraform output -raw create_ai_foundry_resources 2>$null
$foundryCreated = $createFoundry -eq "true"

if ($foundryCreated) {
    $projectName = terraform output -raw ai_foundry_project_name 2>$null
    $hubName = terraform output -raw ai_foundry_hub_id 2>$null
    $aiServicesName = terraform output -raw ai_foundry_ai_services_name 2>$null
    $modelDeployment = terraform output -raw ai_foundry_model_deployment_name 2>$null
    
    Write-Success "Terraform created the following Foundry resources:"
    Write-Host "  - AI Hub: $hubName" -ForegroundColor Gray
    Write-Host "  - AI Project: $projectName" -ForegroundColor Gray
    Write-Host "  - AI Services: $aiServicesName" -ForegroundColor Gray
    if ($modelDeployment -and $modelDeployment -ne "null") {
        Write-Host "  - Model Deployment: $modelDeployment" -ForegroundColor Gray
    }
    Write-Host ""
}
else {
    Write-Warning-Custom "Terraform did NOT create Foundry resources (create_ai_foundry_resources=false)"
    Write-Info "You must create Hub and Project manually at https://ai.azure.com"
    Write-Host ""
}

Write-Host "Manual Steps (Azure AI Portal at https://ai.azure.com):" -ForegroundColor Cyan
Write-Host ""

if ($foundryCreated) {
    Write-Host "1. Navigate to your project:" -ForegroundColor White
    Write-Host "   - Go to https://ai.azure.com" -ForegroundColor Gray
    Write-Host "   - Open project: $projectName" -ForegroundColor Gray
}
else {
    Write-Host "1. Create Azure AI Hub and Project:" -ForegroundColor White
    Write-Host "   - Go to https://ai.azure.com" -ForegroundColor Gray
    Write-Host "   - Create new Hub + Project" -ForegroundColor Gray
}

Write-Host ""
Write-Host "2. Create a Foundry Agent:" -ForegroundColor White
Write-Host "   - In your project, go to 'Agents'" -ForegroundColor Gray
Write-Host "   - Click 'Create new agent'" -ForegroundColor Gray
Write-Host "   - Name it (e.g., 'Servicing Assessment Agent')" -ForegroundColor Gray

Write-Host ""
Write-Host "3. Add OpenAPI Tool to the Agent:" -ForegroundColor White
Write-Host "   - In the agent editor, click 'Add tool' or 'Tools' tab" -ForegroundColor Gray
Write-Host "   - Select 'OpenAPI spec'" -ForegroundColor Gray
Write-Host "   - Upload file: $outputPath" -ForegroundColor Yellow
Write-Host "   - Tool name: 'Vikas lender servicing tools' (or custom)" -ForegroundColor Gray

Write-Host ""
Write-Host "4. Configure Function App Authentication:" -ForegroundColor White
Write-Host "   - The OpenAPI spec requires 'x-functions-key' header authentication" -ForegroundColor Gray
Write-Host "   - In Foundry, create a PROJECT CONNECTION:" -ForegroundColor Gray
Write-Host "     * Type: API Key" -ForegroundColor Gray
Write-Host "     * Header name: x-functions-key" -ForegroundColor Gray
if ($functionKey) {
    Write-Host "     * Header value: $functionKey" -ForegroundColor Yellow
}
else {
    Write-Host "     * Header value: <retrieve manually - see above>" -ForegroundColor Red
}
Write-Host "   - Select this connection for the OpenAPI tool" -ForegroundColor Gray
Write-Host "   - DO NOT paste the key directly into the OpenAPI spec JSON" -ForegroundColor Red

Write-Host ""
Write-Host "5. Paste Agent Instructions:" -ForegroundColor White
$instructionsPath = Join-Path $OutputDir "PASTE-THIS-INTO-FOUNDRY-AGENT-INSTRUCTIONS.txt"
if (Test-Path $instructionsPath) {
    Write-Host "   - Copy content from: $instructionsPath" -ForegroundColor Gray
}
else {
    Write-Host "   - Copy content from: foundry/agent-instructions.md (or similar)" -ForegroundColor Gray
}
Write-Host "   - Paste into the 'Instructions' or 'System prompt' field" -ForegroundColor Gray

Write-Host ""
Write-Host "6. Test the Agent:" -ForegroundColor White
Write-Host "   - Use the test chat in Foundry portal" -ForegroundColor Gray
Write-Host "   - Try: 'Extract statements from vikas-samples container'" -ForegroundColor Gray

Write-Host ""
Write-Section "Reference Documentation"
Write-Host "  - Detailed setup: foundry/HOW_TO_HANG_TOOLS.md" -ForegroundColor Gray
Write-Host "  - Function App: https://portal.azure.com (search '$funcAppName')" -ForegroundColor Gray
Write-Host "  - AI Foundry: https://ai.azure.com" -ForegroundColor Gray

Write-Host ""
Write-Section "Security Reminders"
Write-Host "  - Function key is SENSITIVE - do not commit or share publicly" -ForegroundColor Red
Write-Host "  - Generated OpenAPI file $outputPath contains environment URL" -ForegroundColor Yellow
Write-Host "    DO NOT commit this file to Git" -ForegroundColor Red
Write-Host "  - Template openapi-servicing.json is OK to commit (has placeholder URL)" -ForegroundColor Green
Write-Host "  - Add to .gitignore: foundry/openapi-servicing-*.json" -ForegroundColor Yellow

if ($functionKey) {
    Write-Host ""
    Write-Warning-Custom "FUNCTION KEY FOR MANUAL USE:"
    Write-Host $functionKey -ForegroundColor Yellow
    Write-Host ""
    Write-Host "Copy this key and paste it into the Foundry PROJECT CONNECTION (step 4 above)" -ForegroundColor Cyan
}

Write-Host ""
Write-Success "Configuration script complete!"
Write-Info "Follow the manual steps above to complete Foundry Agent setup."
